version: "3.9"
services:
  pingpang-web:
    image: ccr.ccs.tencentyun.com/weikaisen/pingpang-web:1.0
    container_name: pingpang-web
    networks:
      - pingpang-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - pingpang-storage-volume:/home/storage
      - /opt/pingpang/certificate/www.sysm.ltd:/opt/pingpang/certificate/www.sysm.ltd

networks:
  pingpang-network:
    name: pingpang-network

volumes:
  pingpang-storage-volume:
    name: pingpang-storage-volume
